package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* jueves 13 de octubre de 2016 12:00:57 AM CDT
*/

public interface CalculadoraOperations 
{
  float suma (float valor1, float valor2);
  float resta (float valor1, float valor2);
  float division (float valor1, float valor2);
  float multiplicacion (float valor1, float valor2);
  void shutdown ();
} // interface CalculadoraOperations
