package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* jueves 13 de octubre de 2016 12:00:57 AM CDT
*/

public abstract class CalculadoraPOA extends org.omg.PortableServer.Servant
 implements CalculadoraApp.CalculadoraOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("suma", new java.lang.Integer (0));
    _methods.put ("resta", new java.lang.Integer (1));
    _methods.put ("division", new java.lang.Integer (2));
    _methods.put ("multiplicacion", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CalculadoraApp/Calculadora/suma
       {
         float valor1 = in.read_float ();
         float valor2 = in.read_float ();
         float $result = (float)0;
         $result = this.suma (valor1, valor2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // CalculadoraApp/Calculadora/resta
       {
         float valor1 = in.read_float ();
         float valor2 = in.read_float ();
         float $result = (float)0;
         $result = this.resta (valor1, valor2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // CalculadoraApp/Calculadora/division
       {
         float valor1 = in.read_float ();
         float valor2 = in.read_float ();
         float $result = (float)0;
         $result = this.division (valor1, valor2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // CalculadoraApp/Calculadora/multiplicacion
       {
         float valor1 = in.read_float ();
         float valor2 = in.read_float ();
         float $result = (float)0;
         $result = this.multiplicacion (valor1, valor2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // CalculadoraApp/Calculadora/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/Calculadora:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculadora _this() 
  {
    return CalculadoraHelper.narrow(
    super._this_object());
  }

  public Calculadora _this(org.omg.CORBA.ORB orb) 
  {
    return CalculadoraHelper.narrow(
    super._this_object(orb));
  }


} // class CalculadoraPOA
